#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🧪 Checking format, linting and types...';

cd frontend

echo '🧪 Checking types...';

yarn type-check ||
(
  echo '❌ Typescript type checking failed';
  false;
)

yarn lint-staged
